### ISSUE TITLE
Issue with Study function 

### ISSUE THREAD

**Issue by MatMascelloni** [MIA-iEEG/mia#37]
When I try to create a study, using 1000 repetition, -1.0 to -0.05 baseline and time from -0.500  to 1.5, all I get is signal till 600 ms cid:image001.png@01D7D3CE.9981BFE0

**Comment by annesodub** [comment]
Hi Matteo,

Thank you for your message, so after discussing with you over a visio, we found out that the files you are computing were recorded at different sampling rates. In order to handle this situation in MIA, I added a column in MIA main table such that :

1. You can see the datasets sampling rate, and 
2. The program prevents you from creating a group study with heterogeneous sampling rates.

Please find these modifications in the last version (following this PR : https://github.com/MIA-iEEG/mia/pull/40#issue-776514230) 

Now for your data, I recommend that you resample all your datasets (at the lowest sampling rate accross all your datasets) using your favorite pre-processing software prior to import in MIA (e.g. Brainstorm -> Pre-process -> Resample) .

I hope it helps.
AnneSo
