### ISSUE TITLE
Minor error when importing BST to MIA

### ISSUE THREAD

**Issue by avolfart** [MIA-iEEG/mia#97]
Hi, 
I noticed a small error in the datafiles that are imported from Brainstorm to MIA. It is likely to be harmless but I thought it might be good to report it just in case. 
I imported several patients in MIA from Brainstorm in one go and I noticed in the patient's MIA mat file that the variable "bst_history" has the same size for every patient, e.g., for patient 1, "bst_history" is a 1x47 cell variable and df variable indicating the number of trials is 47, all good. However, for patient 2, "bst_history" is still a 1x47 cell variable while the df variable is now 39 (less trials). Which means there are 8 cells that shouldn't be there for patient 2. Looking further into "bst_history", it seems that the first 39 cells contain the correct info from patient 2 but the last 8 cells are values that have been kept from patient 1. 
Hope this helps!
Angelique

**Comment by annesodub** [comment]
Hi Apoline, 

First of all, many thanks for your valuable feedback, and my apologies for the delayed response.  

Good catch! I was not using very much the bst_history.. I now save it in a structure filed bst_history which size is nHistoryOperations x 3 x nEpochs.

By default Brainstorm keeps an history of the operations which were previously computed on each single trial files in a nOperations x 3 structure. Since we are averaging in MIA we could have left only one. However, in order to leave the user the possibility to get back to the single trial information, I left all trials history. 

To use the latest version, please update mia from Brainstorm menu Plugins --> sEEG --> mia --> Update 

I hope it is ok with you, otherwise please let me know, I am happy to modify the code based on you needs.

Best, AnneSo
